### PR TITLE
Implementing `--theme` custom property

### LINKED ISSUE #12: Propagate `theme` attribute to themable parts
The idea is to change the API so as themes added/removed in the component are propagated to every children that extends the themable-mixin.

With this solution for example we could have different date-pickers in the same page where each one have different appearance for the vaadin-month-calendar, vaadin-button, etc.

### PR DESCRIPTION
**Pull request by manolo**
Connected to https://github.com/vaadin/components-team-tasks/issues/273

Fixes #12 

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-themable-mixin/16)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-themable-mixin.html, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-Ku4i503cLfL7blUqtDh:-Ku4i503cLfL7blUqtDi:b-xcuno4) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/7106b5b549e610fe5400d5c4925b4ff37e15620b/vaadin-themable-mixin.html#L12)):*
> ```HTML
>     static get properties() {
>       return {
>         theme: {
> ```

I don't think this property should be in our components APIs. Just use the native attribute accessors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[vaadin-themable-mixin.html, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-Ku4i503cLfL7blUqtDh:-Ku4nSkFaXI00I4DhQFL:b-896fix) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/7106b5b549e610fe5400d5c4925b4ff37e15620b/vaadin-themable-mixin.html#L12)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I don't think this property should be in our components APIs. Just use the native attribute accessors.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16)*

**Comment by platosha** [comment]
Feels a bit dangerous. I need more prototyping to buy this idea. Currently, on a general level I feel like this would quickly get out-of-control propagating `theme="..."` values deep where they might be unwanted.

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-themable-mixin.html, line 51 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-Ku4prxhOgDNme3BbNg5:-Ku4prxhOgDNme3BbNg6:b-n2fm4a) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/7106b5b549e610fe5400d5c4925b4ff37e15620b/vaadin-themable-mixin.html#L51)):*
> ```HTML
>     ready() {
>       super.ready();
>       this.updateStyles();
> ```

When receiving `--theme` value from the parent CSS scope, `ready` could be too early, because parent styles are only available after it was attached.

Consider `<my-element>` theme that wants to add a theme attribute to the `<themed-element>`s specifically `<my-element>` component:

```
<dom-module id="..." theme-for"my-element">
  <template>
    <style>
      themed-element {
        --theme: 'foo';
      }
    </style>
</dom-module>
```

```
const themedElement = document.createElement('themed-element'); // invokes ready
myElement.shadowRoot.appendChild(themedElement); // this is when the parent styles apply
```

More accurate is “next render” after connected callback, I believe.

---

*[vaadin-themable-mixin.html, line 61 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-Ku4n02zaH_ivDXsJo-S:-Ku4n02zaH_ivDXsJo-T:bvr3zkp) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/7106b5b549e610fe5400d5c4925b4ff37e15620b/vaadin-themable-mixin.html#L61)):*
> ```HTML
>       const computedTheme = this._getComputedStyle(`--theme`);
>       // We only update theme attribute if the current theme does not includes the computed value
>       if (computedTheme && !RegExp(`(^| )${computedTheme}( |$)`).test(currentTheme)) {
> ```

Feels like this has to split by whiespace, merge together, removing duplicates. Simple RegExp substring check could give false negative.

Consider:
```
<themed-element theme="foo bar"></themed-element>
```

```
:host {
  --theme: 'baz bar';
}
```

Moreover, apparently CSS can concatenate strings: http://jsbin.com/sosaceyame/edit?css,output

---

*[test/basic.html, line 23 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-Ku4v_bOqV_qSBN15TLN:-Ku4v_bOqV_qSBN15TLO:bvl9qgs) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/7106b5b549e610fe5400d5c4925b4ff37e15620b/test/basic.html#L23)):*
> ```HTML
>             display: block;
>             --theme: 'foo';
>             --test-qux-theme: 'qux';
> ```

Is this intened to match the use case 2 from here: https://github.com/vaadin/vaadin-themable-mixin/issues/12#issuecomment-327806132?

Does not match, IMO, this should probably test for setting themes for the scoped elements:

```
test-bar {
  --theme: 'qux';
}
```

So that only `<test-bar>`s inside `<test-foo>`’s shadow root get the setting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-:-Ku4tFN-tW5S5ZkgdEdU:b9szvzz)*

**Comment by manolo** [comment]
@jouni idea to avoid that a designer could stop propagation by adding `--theme: var(--element-name-theme);`  to their element `:host` selector

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-themable-mixin.html, line 51 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-Ku4prxhOgDNme3BbNg5:-Ku555ZfN5LI_CqH8JqC:b-896fix) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/7106b5b549e610fe5400d5c4925b4ff37e15620b/vaadin-themable-mixin.html#L51)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

When receiving `--theme` value from the parent CSS scope, `ready` could be too early, because parent styles are only available after it was attached.

Consider `<my-element>` theme that wants to add a theme attribute to the `<themed-element>`s specifically `<my-element>` component:

```
<dom-module id="..." theme-for"my-element">
  <template>
    <style>
      themed-element {
        --theme: 'foo';
      }
    </style>
</dom-module>
```

```
const themedElement = document.createElement('themed-element'); // invokes ready
myElement.shadowRoot.appendChild(themedElement); // this is when the parent styles apply
```

More accurate is “next render” after connected callback, I believe.
</blockquote></details>

Done.

---

*[vaadin-themable-mixin.html, line 61 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-Ku4n02zaH_ivDXsJo-S:-Ku5Ie1D0PhJ6v0lwVxT:b-896fix) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/7106b5b549e610fe5400d5c4925b4ff37e15620b/vaadin-themable-mixin.html#L61)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Feels like this has to split by whiespace, merge together, removing duplicates. Simple RegExp substring check could give false negative.

Consider:
```
<themed-element theme="foo bar"></themed-element>
```

```
:host {
  --theme: 'baz bar';
}
```

Moreover, apparently CSS can concatenate strings: http://jsbin.com/sosaceyame/edit?css,output
</blockquote></details>

Done.

---

*[test/basic.html, line 23 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-Ku4v_bOqV_qSBN15TLN:-Ku5L4_mPD_OV2sD6ruK:b-vulybt) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/7106b5b549e610fe5400d5c4925b4ff37e15620b/test/basic.html#L23)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Is this intened to match the use case 2 from here: https://github.com/vaadin/vaadin-themable-mixin/issues/12#issuecomment-327806132?

Does not match, IMO, this should probably test for setting themes for the scoped elements:

```
test-bar {
  --theme: 'qux';
}
```

So that only `<test-bar>`s inside `<test-foo>`’s shadow root get the setting.
</blockquote></details>

As suggested in chat, I have added a new test that target specific elements in nested shadow. I guess this should cover all use cases

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-:-Ku5LMMoc031rQK8mUVo:beemn6n)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-themable-mixin.html, line 51 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-Ku4prxhOgDNme3BbNg5:-Ku5NyKZkmIrCPpHhLog:b-7anbjq) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/7106b5b549e610fe5400d5c4925b4ff37e15620b/vaadin-themable-mixin.html#L51)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

connected callback does not work, at least in tests. It needs more imports etc. 

ready otherwise in P2 is executed once in the life-cycle of the element, but after the component is attached, and it guarantees that all the polymer api has been loaded.

I dont see the need to replace, unless you can provide a non working example.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-themable-mixin.html, line 51 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-Ku4prxhOgDNme3BbNg5:-Ku61cQv1FB_o9cJN395:b-aza1ih) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/7106b5b549e610fe5400d5c4925b4ff37e15620b/vaadin-themable-mixin.html#L51)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

connected callback does not work, at least in tests. It needs more imports etc. 

ready otherwise in P2 is executed once in the life-cycle of the element, but after the component is attached, and it guarantees that all the polymer api has been loaded.

I dont see the need to replace, unless you can provide a non working example.

</blockquote></details>

Actually is not after the component is attached, but after the dom is ready.
So debugging ready you can check that it's called from `connectedCallback()` -> `_enableProperties()` -> `ready()`
Hence its connectedCallback is earliern than  ready.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16)*

**Comment by platosha** [comment]
:lgtm: 

---

Reviewed 1 of 3 files at r1, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-themable-mixin.html, line 51 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-Ku4prxhOgDNme3BbNg5:-KuJ8FcA7bEolPy5_cAZ:bvc9ddt) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/7106b5b549e610fe5400d5c4925b4ff37e15620b/vaadin-themable-mixin.html#L51)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Actually is not after the component is attached, but after the dom is ready.
So debugging ready you can check that it's called from `connectedCallback()` -> `_enableProperties()` -> `ready()`
Hence its connectedCallback is earliern than  ready.
</blockquote></details>

OK Fair enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/16#-:-KuJ8U3SMAq3llTDuD-p:bg7igkv)*

**Pull request merged**
