### PR TITLE
Fix Travis tests script and prepare for npm packaging

### LINKED ISSUE #22: Ensure Polymer 3 Modulizer compatibility
See "Generic steps" at https://github.com/vaadin/components-team-tasks/issues/326

### PR DESCRIPTION
**Pull request by platosha**
Fixes #22 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-themable-mixin/24)

### CODE REVIEW

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-themable-mixin/24#-:-L8WHhV6BnsLOfGNAFLS:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[.travis.yml, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/24#-L8WHhdrR6EdXGqaPB-G:-L8WHhdsF3KDfdPoS8k6:b1sdhfd) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/201a1d6153849109982f29d4f432577ab6404d7c/.travis.yml#L15)):*
> ```YAML
> 
> before_script:
>   - npm install bower polymer-cli -g
> ```

BTW maybe `polymer-cli@next`?

---

*[package.json, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/24#-L8WCKPJz3VrRIpCfD8E:-L8WCKPJz3VrRIpCfD8F:b-b1nqsc) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/ae7d7f72d2c8fd9e3ca85b75fb4f2478c9b83a48/package.json#L31)):*
> ```JSON
>     "gulp-html-extract": "^0.3.0",
>     "gulp-stylelint": "^7.0.0",
>     "polymer-cli": "^1.6.0",
> ```

BTW the modulizer entry below should also be removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/24)*

**Comment by platosha** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/24#-L8WHhdrR6EdXGqaPB-G:-L8WJ8YRQeKhPkmIcSy_:b-6kgwfw) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/201a1d6153849109982f29d4f432577ab6404d7c/.travis.yml#L15)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW maybe `polymer-cli@next`?
</blockquote></details>

Was broken in the CI last week, so maybe not.

---

*[package.json, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/24#-L8WCKPJz3VrRIpCfD8E:-L8WJDWBJ-dc7oW7mJRa:b-896fix) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/ae7d7f72d2c8fd9e3ca85b75fb4f2478c9b83a48/package.json#L31)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW the modulizer entry below should also be removed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/24)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/24)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/24#-:-L8WKbdXHPq-nQN3H-87:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-themable-mixin/24#-:-L8WLB7f0NXGmRfZJrGH:bnfp4nl)*

**Pull request merged**
