### PR TITLE
Adapt themable mixin to work with Polymer 3

### LINKED ISSUE #22: Ensure Polymer 3 Modulizer compatibility
See "Generic steps" at https://github.com/vaadin/components-team-tasks/issues/326

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #22

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-themable-mixin/23)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/23#-:-L7xxH67uKUQLtf-_mxh:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 1 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-themable-mixin.html, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/23#-L7yT1cHpiRcKfDgMXlX:-L7yR_RI6HQsX5DfyA2U:benath2) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/5293be9547fb9f9f56216dc4d6882c16f829f37e/vaadin-themable-mixin.html#L19)):*
> ```HTML
>       const template = this.prototype._template;
> 
>       const hasOwnTemplate = this.template && this.template.parentElement && this.template.parentElement.id === this.is;
> ```

As of Polymer/polymer#5153 the template finalization has been slightly changed, it now allows resetting parent template. Currently, the following snippet throws:

```js
    class TestNoTemplate extends Vaadin.ThemableMixin(Polymer.Element) {
      static get is() {
        return 'test-no-template';
      }
      static get template() {
        // I don't want your template! Or anyone's template! Leave me alone!
        return null;
      }
    }
    customElements.define(TestNoTemplate.is, TestNoTemplate);
```

We probably need to add another explicit check against that case here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/23)*

**Comment by tomivirkki** [comment]
*[vaadin-themable-mixin.html, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/23#-L7yT1cHpiRcKfDgMXlX:-L7yY3GRc3Wl41YFW-If:b-896fix) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/5293be9547fb9f9f56216dc4d6882c16f829f37e/vaadin-themable-mixin.html#L19)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

As of Polymer/polymer#5153 the template finalization has been slightly changed, it now allows resetting parent template. Currently, the following snippet throws:

```js
    class TestNoTemplate extends Vaadin.ThemableMixin(Polymer.Element) {
      static get is() {
        return 'test-no-template';
      }
      static get template() {
        // I don't want your template! Or anyone's template! Leave me alone!
        return null;
      }
    }
    customElements.define(TestNoTemplate.is, TestNoTemplate);
```

We probably need to add another explicit check against that case here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/23)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/23#-:-L7yedSMig4WMiMPZxzs:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 2 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-themable-mixin/23)*

**Pull request merged**
