### PR TITLE
Include default theme only if it exists

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes https://github.com/vaadin/vaadin-split-layout/issues/77
Fixes https://github.com/vaadin/vaadin-themable-mixin/issues/9
Connects to https://github.com/vaadin/vaadin-element-skeleton/issues/61

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-themable-mixin/18)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/18#-:-KvRxqXmMT4Xp3DK4k-V:bnfp4nl)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[test/basic.html, line 39 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/18#-KvRxuL_2v0RZf0fKBPD:-KvRxuL_2v0RZf0fKBPE:bcgs6fq) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/1c11dfc140054bd7fb24ff8ddb9842a465d613fa/test/basic.html#L39)):*
> ```HTML
>       </template>
>     </dom-module>
>     
> ```

some trailing spaces here, not a blocker of course.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/18)*

**Comment by tomivirkki** [comment]
*[test/basic.html, line 39 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/18#-KvRxuL_2v0RZf0fKBPD:-KvRyPsgp4jSp_cKMhwx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-themable-mixin/blob/1c11dfc140054bd7fb24ff8ddb9842a465d613fa/test/basic.html#L39)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

some trailing spaces here, not a blocker of course.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/18)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themable-mixin/18#-:-KvVoITr7y0BsdKnjm8I:bnfp4nl)*

**Pull request merged**
